### ISSUE TITLE
Benchmark the EFS

### ISSUE THREAD

**Issue by CMCDragonkai** [MatrixAI/js-encryptedfs#76]
Currently the benchmarks don't actually bench the EFS itself.

However it would be dominated by the speed of the crypto and DB. DB already has its own benchmarks, so crypto benchmarks should be removed once crypto is abstracted out when we rework the crypto with PK.

### Tasks

- [ ] 1. Factor out the crypto along with PK to be using WebCrypto along with WASM polyfills
- [ ] 2. Remove crypto benchmarks as that would be in another repo
- [ ] 3. Create EFS benchmarks for reads, writes, random reads and random writes, we can take some tests from existing fs benchmarks

**Comment by CMCDragonkai** [comment]
Based on an initial benchmark in the git/vaults refactoring [ENG-68](https://linear.app/matrix-ai/issue/ENG-68/review-and-refactor-of-gitutilsts-for-serving-vault-git-repositories) [https://github.com/MatrixAI/Polykey/issues/298](https://github.com/MatrixAI/Polykey/issues/298) 

<img src="https://uploads.linear.app/e2a70dcf-d4d4-49a0-8551-1f7b7c87efa2/d0884f84-5288-4728-81bd-cab09fd56c23/5afdc38d-76c8-4909-ac1a-c3cd255ec6ff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2UyYTcwZGNmLWQ0ZDQtNDlhMC04NTUxLTFmN2I3Yzg3ZWZhMi9kMDg4NGY4NC01Mjg4LTQ3MjgtODFiZC1jYWIwOWZkNTZjMjMvNWFmZGMzOGQtNzZjOC00OTA5LWFjMWEtYzNjZDI1NWVjNmZmIiwiaWF0IjoxNzE1NTcyMDE0LCJleHAiOjMzMjg2MTMyMDE0fQ.Kgd2ER8ij5SCTqNXi5LLcodPNypmOKdfTsEog4RRWl4 " alt="image.png" width="482" height="273" />

It's possible that crypto functions results in a 2x speed. However this would be better confirmed by doing it directly on EFS.
